[base_command]
name = "clean"
short = "Remove the artifacts created during the build"

[help]
[help.base]
examples = """Clean the default target directory of the current package.
           $ bal clean

       Clean the provided target directory.
           $ bal clean <target-directory-path>"""
long = """Remove the 'target' directory created during the build. This will delete
       all files and directories in the target directory.

       The default target directory that will be cleaned is the
       '<package-root>/target'. You may also provide a custom target to be
       cleaned."""
synopsis = "bal clean [OPTIONS]"

[[base_command.flag]]
default_val = ""
name = "target-dir"
usage = "Target directory path."
short = "add a meaningfull short message about flag"
