[base_command]
name = "pull"
short = """Fetch packages from Ballerina Central or a custom
       package repository"""

[help]
[help.base]
examples = """Pull the latest version of the 'gmail' connector in the 'wso2'
       organization from Ballerina Central.
           $ bal pull wso2/gmail

       Pull the '1.1.0' version of the 'gmail' connector in the 'wso2'
       organization from Ballerina Central.
           $ bal pull wso2/gmail:1.1.0

       Pull the '1.1.0' version of the 'gmail' connector in the 'wso2'
       organization from the github package repository defined in the Settings.toml file.
           $ bal pull wso2/gmail:1.1.0 --repository=wso2
"""
long = """Download the specified package from Ballerina Central along with its
       dependencies and cache it in the '.ballerina' directory in the user home.

       Ballerina Central is a package repository hosted at
       https://central.ballerina.io/. A package repository organizes packages
       into a three-level hierarchy: organization, package name, and version.
       Organizations are unique within a repository and can be mapped to an
       individual user or organization registered with the repository.

       To download a package from a custom repository, configure it in the Settings.toml
       file and pass the given id with the --repository flag."""
synopsis = "bal pull <org-name>/<package-name>[:<version>]"

[[base_command.flag]]
default_val = ""
name = "repository"
usage = """Pull a package from a custom repository.
        The repository must be configured in the <USER_HOME>/.ballerina/Settings.toml file."""
short = "add a meaningfull short message about flag"
