[base_command]
name = "push"
short = """Push the Ballerina Archive (BALA) of the current package
       to a package repository"""
[help]
[help.base]
examples = """Push the BALA of the current package to Ballerina Central.
       The 'bal pack' command should be run before executing this.
           $ bal push

       Push the BALA of the current package to the local repository for testing.
           $ bal push --repository=local

       Push the provided BALA file. The file path can be relative or absolute.
           $ bal push <bala-path>"""
long = """Push the Ballerina archive (.bala) of the current package to Ballerina
       Central, local or a custom remote repository. Once the package is pushed to Ballerina
       Central, it becomes public and sharable and will be permanent.

       To be able to publish a package to Ballerina Central, you should sign in
       to Ballerina Central and obtain an access token.

       To be able to publish a package to a custom remote repository, it must be defined
       in the <USER_HOME>/.ballerina/Settings.toml file."""
synopsis = "bal push [OPTIONS] <bala-path>"

[[base_command.flag]]
default_val = ""
name = "repository"
usage = """Push the BALA of the current package to a custom repository.
           Only 'local' and repositories specified in the Settings.toml are allowed."""
short = "add a meaningfull short message about flag"
