[base_command]
name = "version"
short = "Print the Ballerina version"

[help]
[help.base]
long = """Print the Ballerina distribution version and the supported
       language specification version.

       Note: The 'bal -v' and 'bal --version' commands are
       identical to 'bal version'."""
synopsis = "bal version"
