name: Daily unit-test run with SemTypes activated

on:
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # random number
    if: github.ref == 'refs/heads/nutcracker' # only run on nutcracker branch
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew semtypesUnitTest configure-on-demand --no-daemon
